### PR TITLE
sv1.3.14.19, Toontown German Client, Donated by Bob-by

### PR DESCRIPTION
**Pull request by furtabs**
Migrated from Tooniarchive.

Not trying to win Hacktober just figured seperate PRs will be easier for you to review.

### CODE REVIEW

**Comment by Bob-by** [comment]
I think you got the names of the client donator wrong on the 2006 DE client.

**Comment by furtabs** [comment]
This is the ZIP i got from him himself. https://drive.google.com/drive/u/1/folders/1wx6vq1GW9u_e2nP1IdiItL6QVCdmkfaV. If you have other evidence please show

**Comment by furtabs** [comment]
Actually crap you might be right. This could be Frizzy's. There is two german clients known. One is Cotes one is his, i might of mixed them up.

**Comment by furtabs** [comment]
Oh wow you are right. Thank you @Bob-by

**Comment by Bob-by** [comment]
I more meant that the client came from me, John Cote had the 2005 March client and Frizzy got the 2006 client from me on March 5 2020

**Comment by furtabs** [comment]
ohh i see now

**Comment by CrankySupertoon** [comment]
@Bob-by mind giving me your email so i can spoof the commit correctly.

**Pull request merged**
